all:
#borderify.js  manifest.json  settings
	rm -rf firefox-wifi.zip
	zip firefox-wifi.zip autologin.js
	zip -u firefox-wifi.zip manifest.json
	zip -u -r firefox-wifi.zip options.js
	zip -u -r firefox-wifi.zip options.html
	zip -u -r firefox-wifi.zip icon48.png
	zip -u -r firefox-wifi.zip icon96.png

